name: CI/CD Try1
on: push

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev

  deploy-staging:
    needs: deploy-dev
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging

  deploy-prod:
    needs: deploy-staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
